name: dStor-node-api CI deploy to MAINNET

# **What it does**: Deploys the API to the mainnet OBE when a release has been approved by two users and released.
# **Why we have it**: Automatic updates to mainnet.
# **Who does it impact**: All mainnet users and work will be affected by this update. The update has been shortened to minimize any downtime.

on:
  push:
    branches: [ main, master ]
jobs:

  apply_to_MN:
    runs-on: ubuntu-latest
    steps:
    - name: update remote repo
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script_stop: true
        script: |
          cd open-block-explorer
          cp .env  ~/obe.env
          git pull --autostash
          cp ~/obe.env .env
          rm -rf dist/spa/*
          source ~/.nvm/nvm.sh
          nvm use 20
          yarn install
          yarn build
          node -v
